name: synra
description: SYNRA video analysis application
publish_to: "none" # Remove this line if you want to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  google_fonts: ^8.0.1
  sensors_plus: ^7.0.0
  path_provider: ^2.1.5
  video_player: ^2.10.1
  camera: ^0.11.3+1
  photo_manager: ^3.8.3
  path: ^1.9.1
  provider: ^6.1.5+1
  dropbox_client: ^1.2.0
  environment_sensors: ^0.3.0
  csv: ^7.2.0
  dio: ^5.9.2
  file_picker: ^10.3.10
  shared_preferences: ^2.5.4
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/synra_logo.png